[versions]
kotlinversion = "2.2.21"
ktfmt = "0.47"
dokka = "2.1.0"
build-config = "6.0.3"
maven-publish = "0.35.0"
spotless = "8.1.0"

auto-service = "1.1.1"
kotlin-compiler-extensions = "0.10.0+2.2.21"
junit-jupiter = "6.0.1"
kctfork = "0.11.1"
kotlin-logging-jvm = "7.0.13"
logback = "1.5.21"

[libraries]
auto-service = { group = "com.google.auto.service", name = "auto-service", version.ref = "auto-service" }
auto-service-annotations = { group = "com.google.auto.service", name = "auto-service-annotations", version.ref = "auto-service" }
kotlin-compiler-extensions = { group = "com.javiersc.kotlin", name = "kotlin-compiler-extensions", version.ref = "kotlin-compiler-extensions" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }
kctfork = { group = "dev.zacsweers.kctfork", name = "core", version.ref = "kctfork" }
kotlin-logging-jvm = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging-jvm" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
build-config = { id = "com.github.gmazzo.buildconfig", version.ref = "build-config" }
maven-publish = { id = "com.vanniktech.maven.publish.base", version.ref = "maven-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
